name: Firebase Smart Cleanup

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: # Nút bấm chạy thủ công

jobs:
  smart_clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Run Cleanup Script
        env:
          # Bạn cần dán nội dung Service Account JSON vào Secret này trong Settings GitHub
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node .github/workflows/cleanup.js
